'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace ZakazivanjePregleda

    Partial Public Class ZakazivanjePregledaEntities8
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=ZakazivanjePregledaEntities8")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property tblHronicnaBolests() As DbSet(Of tblHronicnaBolest)
        Public Overridable Property tblKartons() As DbSet(Of tblKarton)
        Public Overridable Property tblLekars() As DbSet(Of tblLekar)
        Public Overridable Property tblOsiguranjes() As DbSet(Of tblOsiguranje)
        Public Overridable Property tblPacijents() As DbSet(Of tblPacijent)
        Public Overridable Property tblUstanovas() As DbSet(Of tblUstanova)
        Public Overridable Property tblZakPregledas() As DbSet(Of tblZakPregleda)
        Public Overridable Property vwHronicnaBolests() As DbSet(Of vwHronicnaBolest)
        Public Overridable Property vwKartons() As DbSet(Of vwKarton)
        Public Overridable Property vwLekars() As DbSet(Of vwLekar)
        Public Overridable Property vwOsiguranjes() As DbSet(Of vwOsiguranje)
        Public Overridable Property vwPacijents() As DbSet(Of vwPacijent)
        Public Overridable Property vwUstanovas() As DbSet(Of vwUstanova)
        Public Overridable Property vwZakazivanjePregledas() As DbSet(Of vwZakazivanjePregleda)
    
    End Class

End Namespace
