'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class tblHronicnaBolest
        Public Property HronicnaBolestID As Integer
        Public Property DijagnozaBolesti As String
        Public Property DatumPostavljanja As Date
        Public Property Terapija As String
        Public Property DatumPoslednjeKontrole As Date
    
        Public Overridable Property tblKartons As ICollection(Of tblKarton) = New HashSet(Of tblKarton)
    
    End Class

End Namespace
