'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class tblKarton
        Public Property KartonID As Integer
        Public Property Napomena As String
        Public Property HronicnaBolest As Nullable(Of Integer)
        Public Property Visina As Nullable(Of Integer)
        Public Property Tezina As Nullable(Of Integer)
        Public Property Upozorenje As String
        Public Property IzabraniLekar As Nullable(Of Integer)
    
        Public Overridable Property tblHronicnaBolest As tblHronicnaBolest
        Public Overridable Property tblLekar As tblLekar
        Public Overridable Property tblPacijents As ICollection(Of tblPacijent) = New HashSet(Of tblPacijent)
    
    End Class

End Namespace
