'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwHronicnaBolest
        Public Property HronicnaBolestID As Integer
        Public Property DijagnozaBolesti As String
        Public Property DatumPostavljanja As Nullable(Of Date)
        Public Property Terapija As String
        Public Property DatumPoslednjeKontrole As Nullable(Of Date)
    
    End Class

End Namespace
