'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwKarton
        Public Property KartonID As Integer
        Public Property Napomena As String
        Public Property HornicnaBolest As Nullable(Of Integer)
        Public Property Visina As Nullable(Of Integer)
        Public Property Tezina As Nullable(Of Integer)
        Public Property OsnovOsiguranja As String
        Public Property Upozorenje As String
        Public Property IzabraniLekar As String
        Public Property DijagnozaBolesti As String
        Public Property DatumPoslednjeKontrole As Nullable(Of Date)
    
    End Class

End Namespace
