'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwLekar
        Public Property LekarID As Integer
        Public Property Ime As String
        Public Property Prezime As String
        Public Property Specijalista As String
        Public Property Ustanova As Nullable(Of Integer)
        Public Property VrstaUstanove As String
        Public Property Adresa As String
    
    End Class

End Namespace
