'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwOsiguranje
        Public Property OsiguranjeID As Integer
        Public Property VrstaOsiguranja As String
        Public Property BrojPolise As Nullable(Of Integer)
        Public Property IzdavacOsiguranja As String
        Public Property DatumIzdavanjaOsiguranja As Nullable(Of Date)
        Public Property DatumIstekaOsiguranja As Nullable(Of Date)
    
    End Class

End Namespace
