'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwUstanova
        Public Property UstanovaID As Integer
        Public Property Adresa As String
        Public Property VrstaUstanove As String
        Public Property Direktor As String
    
    End Class

End Namespace
