'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ZakazivanjePregleda

    Partial Public Class vwZakazivanjePregleda
        Public Property ZakazivanjeID As Integer
        Public Property Lekar As Nullable(Of Integer)
        Public Property Pacijent As Nullable(Of Integer)
        Public Property DatumPocetkaPregleda As Nullable(Of Date)
        Public Property DatumZavrsetkaPregleda As Nullable(Of Date)
        Public Property Ime As String
        Public Property Prezime As String
        Public Property LBO As Nullable(Of Integer)
        Public Property Ustanova As Nullable(Of Integer)
        Public Property Expr1 As String
        Public Property Specijalista As String
    
    End Class

End Namespace
